// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webMail.Server.DbContexts;

#nullable disable

namespace webMail.Server.Migrations
{
    [DbContext(typeof(WebMailDbContext))]
    [Migration("20240723081003_AddMailHistoryTable")]
    partial class AddMailHistoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("webMail.Server.Models.MailHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dt");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("subject");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("to_email");

                    b.Property<Guid>("sender")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("sender");

                    b.ToTable("mail_history");
                });

            modelBuilder.Entity("webMail.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("webMail.Server.Models.MailHistory", b =>
                {
                    b.HasOne("webMail.Server.Models.User", "Sender")
                        .WithMany("MailHistories")
                        .HasForeignKey("sender")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("webMail.Server.Models.User", b =>
                {
                    b.Navigation("MailHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
